#ENV["CONSUMER_KEY"]        = "yourc0nsum3key"
#ENV["CONSUMER_SECRET"]     = "yourconsumers3cr3t"
#ENV["ACCESS_TOKEN"]        = "youraccesst0k3n"
#ENV["ACCESS_TOKEN_SECRET"] = "t0k3ns3cr3t"
#ENV["TWITTER_ACCOUNT"]     = "name_of_your_account"
